baseURL = 'https://iampervaze.github.io/'
languageCode = 'en-us'
title = 'ahanger'
theme = 'hugo-paper'
author = 'iampervaze'
description = 'blog'

[params]
  author = "Pervaze Ahanger"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/iampervaze"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/iampervaze"
